<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="chilitag" >

  
  <xacro:macro name="chilitag_visual_sized" params="name size *origin">
    <visual>
      <xacro:insert_block name="origin" />
      <geometry>
        <mesh scale="${size} ${size} ${size}" filename="package://hector_chilitag_description/meshes/${name}.dae"/>
      </geometry>
    </visual>
  </xacro:macro>
  
  <xacro:macro name="chilitag_no_geom" params="name size parent *origin">
    
    <joint name="${name}_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_link"/>
    </joint>
      
    <link name="${name}_link">      
    </link>
 
    <gazebo reference="${name}_link">
    </gazebo>
    
  </xacro:macro>
  
  
  <xacro:macro name="chilitag" params="name size parent *origin">
    
    <joint name="${name}_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_link"/>
    </joint>
      
    <link name="${name}_link">
      <inertial>
        <origin xyz="0 0 0" /> 
        <mass value="0.01" />
        <inertia  ixx="0.00000001" ixy="0.0"  ixz="0.0"  iyy="0.00000001"  iyz="0.0"  izz="0.00000001" />
      </inertial>
      
      <xacro:chilitag_visual_sized name="${name}" size="${size}">
        <origin xyz="0 0 0" rpy="0 -1.57079632679 0"/>
      </xacro:chilitag_visual_sized>
      <!--
      <visual>
        <origin xyz="0 0 0" rpy="0 -1.57079632679 0"/>
        <geometry>
          <mesh scale="${size} ${size} ${size}" filename="package://hector_chilitag_description/meshes/${name}.dae"/>
        </geometry>
      </visual>
      -->
      <!--
      <collision>
        <origin xyz="0 0 0" rpy="0 -1.57079632679 0"/>
        <geometry>
          <mesh scale="${size} ${size} ${size}" filename="package://hector_chilitag_description/meshes/${name}.dae"/>
        </geometry>
      </collision>
      -->
    </link>
 
    <gazebo reference="${name}_link">
    </gazebo>
    
  </xacro:macro>
  
    <xacro:macro name="chilitag3d" params="name size parent *origin">
    
    <joint name="${name}_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_link"/>
    </joint>
      
    <link name="${name}_link">
      <inertial>
        <origin xyz="0 0 0" /> 
        <mass value="0.01" />
        <inertia  ixx="0.00000001" ixy="0.0"  ixz="0.0"  iyy="0.00000001"  iyz="0.0"  izz="0.00000001" />
      </inertial>
      
      <xacro:chilitag_visual_sized name="${name}" size="${size}">
        <origin xyz="${size/2} ${size/2} 0" rpy="${-M_PI/2} ${M_PI/2} ${M_PI}"/>
      </xacro:chilitag_visual_sized>
    </link>
 
    <gazebo reference="${name}_link">
    </gazebo>
    
  </xacro:macro>

  <xacro:macro name="multi_chilitag" params="name size parent *origin">

    <joint name="${parent}_${name}_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${parent}_${name}_link"/>
    </joint>

    <link name="${parent}_${name}_link">
      <inertial>
        <origin xyz="0 0 0" />
        <mass value="0.01" />
        <inertia  ixx="0.00000001" ixy="0.0"  ixz="0.0"  iyy="0.00000001"  iyz="0.0"  izz="0.00000001" />
      </inertial>

      <xacro:chilitag_visual_sized name="${name}" size="${size}">
        <origin xyz="${size/2} ${size/2} 0" rpy="${-M_PI/2} ${M_PI/2} ${M_PI}"/>
      </xacro:chilitag_visual_sized>
    </link>

    <gazebo reference="${parent}_${name}_link">
    </gazebo>

  </xacro:macro>
    
</robot>
