<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro" name="chilitag" >

  
  <xacro:macro name="chilitag_visual_sized" params="name size *origin">
    <visual>
      <xacro:insert_block name="origin" />
      <geometry>
        <mesh scale="${size} ${size} ${size}" filename="package://hector_chilitag_description/meshes/${name}.dae"/>
      </geometry>
    </visual>
  </xacro:macro>
  
  <xacro:macro name="chilitag_no_geom" params="name size parent *origin">
    
    <joint name="${name}_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_link"/>
    </joint>
      
    <link name="${name}_link">      
    </link>
 
    <gazebo reference="${name}_link">
    </gazebo>
    
  </xacro:macro>
  
  
  <xacro:macro name="chilitag" params="name size parent *origin">
    
    <joint name="${name}_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_link"/>
    </joint>
      
    <link name="${name}_link">
      <inertial>
        <origin xyz="0 0 0" /> 
        <mass value="0.01" />
        <inertia  ixx="0.00000001" ixy="0.0"  ixz="0.0"  iyy="0.00000001"  iyz="0.0"  izz="0.00000001" />
      </inertial>
      
      <xacro:chilitag_visual_sized name="${name}" size="${size}">
        <origin xyz="0 0 0" rpy="0 -1.57079632679 0"/>
      </xacro:chilitag_visual_sized>
      <!--
      <visual>
        <origin xyz="0 0 0" rpy="0 -1.57079632679 0"/>
        <geometry>
          <mesh scale="${size} ${size} ${size}" filename="package://hector_chilitag_description/meshes/${name}.dae"/>
        </geometry>
      </visual>
      -->
      <!--
      <collision>
        <origin xyz="0 0 0" rpy="0 -1.57079632679 0"/>
        <geometry>
          <mesh scale="${size} ${size} ${size}" filename="package://hector_chilitag_description/meshes/${name}.dae"/>
        </geometry>
      </collision>
      -->
    </link>
 
    <gazebo reference="${name}_link">
    </gazebo>
    
  </xacro:macro>

  <xacro:macro name="chilitag_origin_in_corner" params="name size parent *origin">

    <joint name="${name}_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_link"/>
    </joint>

    <link name="${name}_link">
      <inertial>
        <origin xyz="${size/2} ${size/2} 0" />
        <mass value="0.01" />
        <inertia  ixx="0.00000001" ixy="0.0"  ixz="0.0"  iyy="0.00000001"  iyz="0.0"  izz="0.00000001" />
      </inertial>

      <xacro:chilitag_visual_sized name="${name}" size="${size}">
        <origin xyz="${size/2} ${size/2} 0" rpy="0 -1.57079632679 0"/>
      </xacro:chilitag_visual_sized>
    </link>

    <gazebo reference="${name}_link">
    </gazebo>

  </xacro:macro>

  <xacro:macro name="chilitag_4_set" params="name_start offset_x offset_y offset_z offset_tag size parent">

      <xacro:chilitag_origin_in_corner name="chilitag${name_start}" size="${size}" parent="${parent}">
        <origin xyz="${offset_x}
                     ${offset_y}
                     ${offset_z}"
                rpy="0 0 0"/>
      </xacro:chilitag_origin_in_corner>

      <xacro:chilitag_origin_in_corner name="chilitag${name_start + 1}" size="${size}" parent="${parent}">
        <origin xyz="${offset_x}
                     ${offset_y + offset_tag}
                     ${offset_z}"
                rpy="0 0 0"/>
      </xacro:chilitag_origin_in_corner>

      <xacro:chilitag_origin_in_corner name="chilitag${name_start + 2}" size="${size}" parent="${parent}">
        <origin xyz="${offset_x + offset_tag}
                     ${offset_y}
                     ${offset_z}"
                rpy="0 0 0"/>
      </xacro:chilitag_origin_in_corner>

      <xacro:chilitag_origin_in_corner name="chilitag${name_start + 3}" size="${size}" parent="${parent}">
        <origin xyz="${offset_x + offset_tag}
                     ${offset_y + offset_tag}
                     ${offset_z}"
                rpy="0 0 0"/>
      </xacro:chilitag_origin_in_corner>

  </xacro:macro>

  <xacro:macro name="chilitag_9_set" params="name_start offset_x offset_y offset_z offset_tag size parent">

      <xacro:chilitag_origin_in_corner name="chilitag${name_start}" size="${size}" parent="${parent}">
        <origin xyz="${offset_x}
                     ${offset_y}
                     ${offset_z}"
                rpy="0 0 0"/>
      </xacro:chilitag_origin_in_corner>

      <xacro:chilitag_origin_in_corner name="chilitag${name_start + 1}" size="${size}" parent="${parent}">
        <origin xyz="${offset_x}
                     ${offset_y + offset_tag}
                     ${offset_z}"
                rpy="0 0 0"/>
      </xacro:chilitag_origin_in_corner>

      <xacro:chilitag_origin_in_corner name="chilitag${name_start + 2}" size="${size}" parent="${parent}">
        <origin xyz="${offset_x}
                     ${offset_y + offset_tag * 2}
                     ${offset_z}"
                rpy="0 0 0"/>
      </xacro:chilitag_origin_in_corner>

      <xacro:chilitag_origin_in_corner name="chilitag${name_start + 3}" size="${size}" parent="${parent}">
        <origin xyz="${offset_x + offset_tag}
                     ${offset_y}
                     ${offset_z}"
                rpy="0 0 0"/>
      </xacro:chilitag_origin_in_corner>

      <xacro:chilitag_origin_in_corner name="chilitag${name_start + 4}" size="${size}" parent="${parent}">
        <origin xyz="${offset_x + offset_tag}
                     ${offset_y + offset_tag}
                     ${offset_z}"
                rpy="0 0 0"/>
      </xacro:chilitag_origin_in_corner>

      <xacro:chilitag_origin_in_corner name="chilitag${name_start + 5}" size="${size}" parent="${parent}">
        <origin xyz="${offset_x + offset_tag}
                     ${offset_y + offset_tag * 2}
                     ${offset_z}"
                rpy="0 0 0"/>
      </xacro:chilitag_origin_in_corner>

      <xacro:chilitag_origin_in_corner name="chilitag${name_start + 6}" size="${size}" parent="${parent}">
        <origin xyz="${offset_x + offset_tag * 2}
                     ${offset_y}
                     ${offset_z}"
                rpy="0 0 0"/>
      </xacro:chilitag_origin_in_corner>

      <xacro:chilitag_origin_in_corner name="chilitag${name_start + 7}" size="${size}" parent="${parent}">
        <origin xyz="${offset_x + offset_tag * 2}
                     ${offset_y + offset_tag}
                     ${offset_z}"
                rpy="0 0 0"/>
      </xacro:chilitag_origin_in_corner>

      <xacro:chilitag_origin_in_corner name="chilitag${name_start + 8}" size="${size}" parent="${parent}">
        <origin xyz="${offset_x + offset_tag * 2}
                     ${offset_y + offset_tag * 2}
                     ${offset_z}"
                rpy="0 0 0"/>
      </xacro:chilitag_origin_in_corner>

  </xacro:macro>

  <xacro:macro name="bow" params="name_start offset_tag offset_set_z size parent">

      <xacro:property name="offset_set_1_x" value="0.6105" />
      <xacro:property name="offset_set_1_y" value="-0.0895" />

      <xacro:property name="offset_set_2_x" value="0.4355" />
      <xacro:property name="offset_set_2_y" value="0.4355" />

      <xacro:property name="offset_set_3_x" value="0.4355" />
      <xacro:property name="offset_set_3_y" value="-0.6145" />

      <xacro:property name="offset_set_4_x" value="-0.0895" />
      <xacro:property name="offset_set_4_y" value="0.6105" />

      <xacro:property name="offset_set_5_x" value="-0.0895" />
      <xacro:property name="offset_set_5_y" value="-0.7895" />

      <xacro:property name="offset_set_6_x" value="-0.6145" />
      <xacro:property name="offset_set_6_y" value="0.4355" />

      <xacro:property name="offset_set_7_x" value="-0.6145" />
      <xacro:property name="offset_set_7_y" value="-0.6145" />

      <xacro:chilitag_9_set name_start="${name_start}" offset_x="${offset_set_1_x}" offset_y="${offset_set_1_y}" offset_z="${offset_set_z}" offset_tag="${offset_tag}" size="${size}" parent="${parent}">
      </xacro:chilitag_9_set>

      <xacro:chilitag_9_set name_start="${name_start + 9}" offset_x="${offset_set_2_x}" offset_y="${offset_set_2_y}" offset_z="${offset_set_z}" offset_tag="${offset_tag}" size="${size}" parent="${parent}">
      </xacro:chilitag_9_set>

      <xacro:chilitag_9_set name_start="${name_start + 18}" offset_x="${offset_set_3_x}" offset_y="${offset_set_3_y}" offset_z="${offset_set_z}" offset_tag="${offset_tag}" size="${size}" parent="${parent}">
      </xacro:chilitag_9_set>

      <xacro:chilitag_9_set name_start="${name_start + 27}" offset_x="${offset_set_4_x}" offset_y="${offset_set_4_y}" offset_z="${offset_set_z}" offset_tag="${offset_tag}" size="${size}" parent="${parent}">
      </xacro:chilitag_9_set>

      <xacro:chilitag_9_set name_start="${name_start + 36}" offset_x="${offset_set_5_x}" offset_y="${offset_set_5_y}" offset_z="${offset_set_z}" offset_tag="${offset_tag}" size="${size}" parent="${parent}">
      </xacro:chilitag_9_set>

      <xacro:chilitag_9_set name_start="${name_start + 45}" offset_x="${offset_set_6_x}" offset_y="${offset_set_6_y}" offset_z="${offset_set_z}" offset_tag="${offset_tag}" size="${size}" parent="${parent}">
      </xacro:chilitag_9_set>

      <xacro:chilitag_9_set name_start="${name_start + 54}" offset_x="${offset_set_7_x}" offset_y="${offset_set_7_y}" offset_z="${offset_set_z}" offset_tag="${offset_tag}" size="${size}" parent="${parent}">
      </xacro:chilitag_9_set>

  </xacro:macro>
  
    <xacro:macro name="chilitag3d" params="name size parent *origin">
    
    <joint name="${name}_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_link"/>
    </joint>
      
    <link name="${name}_link">
      <inertial>
        <origin xyz="0 0 0" /> 
        <mass value="0.01" />
        <inertia  ixx="0.00000001" ixy="0.0"  ixz="0.0"  iyy="0.00000001"  iyz="0.0"  izz="0.00000001" />
      </inertial>
      
      <xacro:chilitag_visual_sized name="${name}" size="${size}">
        <origin xyz="${size/2} ${size/2} 0" rpy="${-M_PI/2} ${M_PI/2} ${M_PI}"/>
      </xacro:chilitag_visual_sized>
    </link>
 
    <gazebo reference="${name}_link">
    </gazebo>
    
  </xacro:macro>

  <xacro:macro name="multi_chilitag" params="name size parent *origin">

    <joint name="${parent}_${name}_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${parent}_${name}_link"/>
    </joint>

    <link name="${parent}_${name}_link">
      <inertial>
        <origin xyz="0 0 0" />
        <mass value="0.01" />
        <inertia  ixx="0.00000001" ixy="0.0"  ixz="0.0"  iyy="0.00000001"  iyz="0.0"  izz="0.00000001" />
      </inertial>

      <xacro:chilitag_visual_sized name="${name}" size="${size}">
        <origin xyz="${size/2} ${size/2} 0" rpy="${-M_PI/2} ${M_PI/2} ${M_PI}"/>
      </xacro:chilitag_visual_sized>
    </link>

    <gazebo reference="${parent}_${name}_link">
    </gazebo>

  </xacro:macro>
    
</robot>
